---
title: "Visualization_challenge_partB"
author: "KiseokUchicago"
date: "2020-09-16"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r}
# load libraries
library(ggplot2)
library(cowplot)
library(ggrepel)
library(htmlwidgets)
library(plotly)
```


```{r}
# Import data
# Import pheno.csv
# Read the phenotype data from the CSV file. 
pheno <- read.csv("data/pheno.csv",quote = "",check.names = FALSE,
                  stringsAsFactors = FALSE)

# Remove the data from the methamphetamine sensitivity testing, since
# these data will not be used in the programming challenge. Also, most
# of the data from the prepulse inhibition tests will not be used, so
# we can remove those columns as well.
pheno <- pheno[c(1:38,65:67)]

# Convert some of the columns to factors.
pheno <- transform(pheno,
                   id            = as.character(id),
                   round         = factor(round,paste0("SW",1:25)),
                   FCbox         = factor(FCbox),
                   PPIbox        = factor(PPIbox),
                   methcage      = factor(methcage),
                   methcycle     = factor(methcycle),
                   discard       = factor(discard),
                   mixup         = factor(mixup),
                   earpunch      = factor(earpunch),
                   abnormalbone  = factor(abnormalbone),
                   experimenters = factor(experimenters))

# Convert the "fasting glucose" column to double precision.
pheno <- transform(pheno,fastglucose = as.double(fastglucose))

# Remove rows marked as "discard" and as possible sample mixups.
pheno <- subset(pheno,discard == "no" & mixup == "no")

hmdp <- read.csv("data/hmdp.csv", stringsAsFactors = FALSE)
gwscan <- read.csv("data/gwscan.csv", stringsAsFactors = FALSE)
gwscan <- transform(gwscan, chr = factor(chr, 1:19))

geno <- read.csv("data/geno_rs29477109.csv", stringsAsFactors = FALSE)
geno <- transform(geno, id = as.character(id))
```


# Part B

## 1. Histogram: distribution of BMD in CFW mice

```{r}
head(pheno)
colnames(pheno)
p_bmd <- ggplot(pheno, aes_string(x='BMD')) +
  geom_histogram(fill='darkblue') +
  xlim(c(40,160)) +
  ylim(c(0,200)) +
  labs(x= 'BMD (mg/cm2)', y= 'Frequency', title = "CFW") +
  theme_cowplot()

p_bmd
```

## 2. Compare with the reference distribution

```{r}
# get only the male
head(hmdp)
unique(hmdp$sex)
# hmdp[hmdp$sex == 'M',]

# get the unit equal
hmdp <- hmdp %>% filter(sex == 'M')  %>% mutate(femur_mg = femur *1000)
# hmdp$femur_mg <- hmdp$femur * 1000

p_bmd2 <- ggplot(hmdp, aes_string(x='femur_mg')) +
  geom_histogram(fill='darkblue') +
  xlim(c(40,160)) +
  ylim(c(0,200)) +
  labs(x= 'BMD (mg/cm2)', y= 'Frequency', title = "Reference") +
  theme_cowplot()

p_bmd2

plot_grid(
  p_bmd, p_bmd2,
  labels = "AUTO", ncol = 1
)
```

